### PR TITLE
Gh 561

### LINKED ISSUE #561: error retrieving additional headers secret for DNSHealthCheckProbe
```
2023-09-15T13:16:51Z	ERROR	Reconciler error	{"controller": "dnshealthcheckprobe", "controllerGroup": "kuadrant.io", "controllerKind": "DNSHealthCheckProbe", "DNSHealthCheckProbe": {"name":"172.31.200.0-prod-web-api","namespace":"multi-cluster-gateways"}, "namespace": "multi-cluster-gateways", "name": "172.31.200.0-prod-web-api", "reconcileID": "5592200d-b5c3-4d74-9984-9d7571bcd914", "error": "error retrieving additional headers secret multi-cluster-gateways/probe-headers: Secret \"probe-headers\" not found"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235
2023-09-15T13:16:51Z	ERROR	Reconciler error	{"controller": "dnshealthcheckprobe", "controllerGroup": "kuadrant.io", "controllerKind": "DNSHealthCheckProbe", "DNSHealthCheckProbe": {"name":"172.31.201.0-prod-web-api","namespace":"multi-cluster-gateways"}, "namespace": "multi-cluster-gateways", "name": "172.31.201.0-prod-web-api", "reconcileID": "92920e59-afab-465c-83a0-da678f3b5637", "error": "error retrieving additional headers secret multi-cluster-gateways/probe-headers: Secret \"probe-headers\" not found"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235
```

This error happened during the #515 (deliberately) after adding this to the DNSPolicy
```
  healthCheck:
    additionalHeadersRef:
      name: probe-headers
    allowInsecureCertificates: true
    endpoint: /
    expectedResponses:
    - 200
    - 201
    - 301
    failureThreshold: 1
    port: 443
    protocol: https
```
However, there wasn't any way for me to figure out what was wrong without checking the logs.
A suggestion here is to add a status condition to the DNSHealthCheckProbe or DNSPolicy.
cc @philbrookes

### PR DESCRIPTION
**Pull request by philbrookes**
- Updated required fields in probe status
- Git ignore kubeconfig files.
closes #561

### CODE REVIEW

**Comment by david-martin** [comment]
👀

File: pkg/controllers/dnshealthcheckprobe/dnshealthcheckprobe_controller.go [hunk 1]
```diff
@@ -92,8 +92,15 @@ func (r *DNSHealthCheckProbeReconciler) Reconcile(ctx context.Context, req ctrl.
 	additionalHeaders, err := getAdditionalHeaders(ctx, r.Client, probeObj)
 
 	if err != nil {
-		//update probe status, ignore update errors
-		_ = r.Client.Status().Update(ctx, probeObj)
+		f := false
+		logger.Error(err, "error getting additional headers for probe")
```
Comment (david-martin) [inline pkg/controllers/dnshealthcheckprobe/dnshealthcheckprobe_controller.go:96]: Given the status is available to the user,
and the cause of the error is very likely something the user can/should fix themselves,
I wonder if 'error' level logging is overkill here.
If I was an ops or sre person running this service, I would expect errors to be something I have to react to.
In the case of a missing secret, I can't fix that. The status information on the resource is how the user gets notified.

**Review by david-martin — COMMENTED** [review]
Verified. See 1 comment inline as well.

the error is still showing up in the log
```
2023-09-20T09:50:50Z	ERROR	Reconciler error	{"controller": "dnshealthcheckprobe", "controllerGroup": "kuadrant.io", "controllerKind": "DNSHealthCheckProbe", "DNSHealthCheckProbe": {"name":"172.31.200.0-prod-web-api","namespace":"multi-cluster-gateways"}, "namespace": "multi-cluster-gateways", "name": "172.31.200.0-prod-web-api", "reconcileID": "35a60df6-b69d-4a92-b23e-6a5020a94d33", "error": "error retrieving additional headers secret multi-cluster-gateways/probe-headers: Secret \"probe-headers\" not found"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235
```

and the dnsprobe has a status that looks like this:

```
status:
  healthy: false
  lastCheckedAt: "2023-09-20T09:51:16Z"
  reason: additional headers secret not found
```
